- name: Stop and remove the running containers for frontend, backend and MongoDB, also remove the images
  hosts: all
  become: true
  tasks:
    - name: Set default values if variables are not defined
      set_fact:
        BACKEND_IMAGE: "{{ BACKEND_IMAGE | default('ghcr.io/paulscherrerinstitute/data_board_backend') }}"
        FRONTEND_IMAGE: "{{ FRONTEND_IMAGE | default('ghcr.io/paulscherrerinstitute/data_board_frontend') }}"
        MONGO_IMAGE: "{{ MONGO_IMAGE | default('mongo') }}"
        BACKEND_PORT: "{{ BACKEND_PORT | default(8080) }}"
        BACKEND_HOST: "{{ BACKEND_HOST | default('http://' + ansible_default_ipv4.address) }}"
        FRONTEND_PORT: "{{ FRONTEND_PORT | default(80) }}"
        MONGO_PORT: "{{ MONGO_PORT | default(27017) }}"

    - name: Stop Docker container for frontend
      docker_container:
        name: data_board_frontend
        state: stopped

    - name: Stop Docker container for backend
      docker_container:
        name: data_board_backend
        state: stopped

    - name: Stop Docker container for MongoDB
      docker_container:
        name: data_board_mongo
        state: stopped

    - name: Remove Docker container for frontend
      docker_container:
        name: data_board_frontend
        state: absent

    - name: Remove Docker container for backend
      docker_container:
        name: data_board_backend
        state: absent

    - name: Remove Docker container for MongoDB
      docker_container:
        name: data_board_mongo
        state: absent

    - name: Remove Docker network
      docker_network:
        name: data_board_network
        state: absent
        force: yes

    - name: Remove Docker image for frontend
      docker_image:
        name: "{{ FRONTEND_IMAGE }}"
        state: absent

    - name: Remove Docker image for backend
      docker_image:
        name: "{{ BACKEND_IMAGE }}"
        state: absent

    - name: Remove Docker image for MongoDB
      docker_image:
        name: "{{ MONGO_IMAGE }}"
        state: absent
