services:
  redis:
    image: "${REDIS_IMAGE:-redis}"
    command: ["redis-server", "--save", '""', "--appendonly", "no"]
    ports:
      - "${REDIS_PORT:-6379}:6379"
    restart: unless-stopped
    networks:
      - data_board_network

  backend:
    image: "${BACKEND_IMAGE:-container.psi.ch/controls-ci/data_board_backend}"
    ports:
      - "${BACKEND_PORT:-8080}:8080"
    restart: unless-stopped
    environment:
      REDIS_HOST: "redis"
      REDIS_PORT: "${REDIS_PORT:-6379}"
    networks:
      - data_board_network

  frontend:
    image: "${FRONTEND_IMAGE:-container.psi.ch/controls-ci/data_board_frontend}"
    ports:
      - "${FRONTEND_PORT:-80}:80"
    restart: unless-stopped
    environment:
      DATA_BOARD_PUBLIC_BACKEND_URL: "${BACKEND_HOST:-http://localhost}:${BACKEND_PORT:-8080}"
    networks:
      - data_board_network

networks:
  data_board_network:
    driver: bridge