- name: Stop and remove the running containers for frontend, backend and MongoDB, also remove the images
  hosts: all
  become: true
  tasks:
    - name: Set default values if variables are not defined
      set_fact:
        BACKEND_IMAGE: "{{ BACKEND_IMAGE | default('ghcr.io/paulscherrerinstitute/data_board_backend') }}"
        FRONTEND_IMAGE: "{{ FRONTEND_IMAGE | default('ghcr.io/paulscherrerinstitute/data_board_frontend') }}"
        MONGO_IMAGE: "{{ MONGO_IMAGE | default('mongo') }}"

    - name: Stop containers gracefully
      docker_container:
        name: "{{ item }}"
        state: stopped
      loop:
        - data_board_frontend
        - data_board_backend
        - data_board_mongo
      ignore_errors: yes

    - name: Remove containers
      docker_container:
        name: "{{ item }}"
        state: absent
      loop:
        - data_board_frontend
        - data_board_backend
        - data_board_mongo
      ignore_errors: yes

    - name: Remove network
      docker_network:
        name: data_board_network
        state: absent
        force: yes
      ignore_errors: yes

    - name: Remove images
      docker_image:
        name: "{{ item }}"
        state: absent
      loop:
        - "{{ FRONTEND_IMAGE }}"
        - "{{ BACKEND_IMAGE }}"
        - "{{ MONGO_IMAGE }}"
      ignore_errors: yes
