services:
  mongo:
    image: "${MONGO_IMAGE:-mongo:latest}"
    pull_policy: always
    environment:
      MONGO_INITDB_DATABASE: "${MONGO_DB_NAME:-databoard}"
    restart: unless-stopped
    networks:
      - data_board_network
    volumes:
      - mongo_data_volume:/data/db

  backend:
    image: "${BACKEND_IMAGE:-ghcr.io/paulscherrerinstitute/data_board_backend:latest}"
    pull_policy: always
    restart: unless-stopped
    environment:
      MONGO_HOST: "mongo"
      MONGO_PORT: "27017"
      MONGO_DB_NAME: "${MONGO_DB_NAME:-databoard}"
      SCHEMA_PATH: "${SCHEMA_PATH:-}"
    networks:
      - data_board_network

  frontend:
    image: "${FRONTEND_IMAGE:-ghcr.io/paulscherrerinstitute/data_board_frontend:latest}"
    pull_policy: always
    ports:
      - "${FRONTEND_PORT:-80}:80"
    restart: unless-stopped
    environment:
      DATA_BOARD_INTERNAL_BACKEND_URL: "http://backend:8080"
      DATA_BOARD_PUBLIC_BACKEND_URL: "/api"
    networks:
      - data_board_network

networks:
  data_board_network:
    driver: bridge

volumes:
  mongo_data_volume: